apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hw4.fullname" . }}-frontapp
  labels:
    {{- include "hw4.labels" . | nindent 4 }}
    {{- include "hw4.frontapp.podLabels" . | nindent 4 }}
spec:
  {{- if not .Values.frontapp.autoscaling.enabled }}
  replicas: {{ .Values.frontapp.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hw4.selectorLabels" . | nindent 6 }}
      {{- include "hw4.frontapp.podLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.frontapp.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hw4.labels" . | nindent 8 }}
        {{- include "hw4.frontapp.podLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hw4.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-frontapp
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontapp.image.repository }}:{{ .Values.frontapp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontapp.image.pullPolicy }}
          ports:
            - name: http-frontapp
              containerPort: {{ required "Frontapp container's port is required" .Values.frontapp.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.frontapp.resources | nindent 12 }}
          {{- with .Values.frontapp.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          - name: BACK_URL
            value: http://{{ include "hw4.fullname" . }}-backapp:{{ required "Frontapp service's port is required" .Values.backapp.service.port }}
          - name: APP_DEFAULT_MESSAGE
            value: {{ .Values.frontapp.defaultMessage | default "frontapp" }}
          - name: JAVA_OPTS
            value: {{ .Values.frontapp.javaOpts }}
          {{- range .Values.frontapp.env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}

      {{- with .Values.frontapp.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
