apiVersion: v1
kind: Service
metadata:
  name: {{ include "hw4.fullname" . }}-backapp
  labels:
    {{- include "hw4.labels" . | nindent 4 }}
    {{- include "hw4.backapp.podLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backapp.service.type }}
  ports:
    - port: {{ .Values.backapp.service.port }}
      targetPort: http-backapp
      protocol: TCP
      name: http-backapp
  selector:
    {{- include "hw4.selectorLabels" . | nindent 4 }}
    {{- include "hw4.backapp.podLabels" . | nindent 4 }}
