apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontapp
  labels:
    homework: frontapp
spec:
  replicas: 1
  selector:
    matchLabels:
      homework: frontapp
  template:
    metadata:
      labels:
        homework: frontapp
    spec:
      containers:
        - name: frontapp
          image: quay.io/drsylent/cubix/block3/homework-frontapp:springboot3
          ports:
            - name: frontapp
              containerPort: 8080
          env:
            - name: BACK_URL
              value: http://backapp:8081
            - name: APP_DEFAULT_MESSAGE
              value: frontapp
            - name: JAVA_OPTS
              value: ""
