apiVersion: v1
kind: Service
metadata:
  name: frontapp
  labels:
    homework: frontapp
spec:
  selector:
    homework: frontapp
  ports:
    - name: frontapp
      port: 8080
      targetPort: frontapp
